# Generated by Django 3.2.5 on 2021-11-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
