# Generated by Django 3.2.5 on 2021-11-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('B', 'Bola'), ('P', 'Peso'), ('A', 'Aquático')], default='P', max_length=1)),
            ],
        ),
    ]
